### ISSUE TITLE
Using the dataset for personal projects

### ISSUE THREAD

**Issue by vgherard** [demirbilek95/AI2SWINTERDATATHON_PROBLEM#1]
Hi,

me and my fellow teammates were planning to play a bit further with the model we built for the competition, ideally to publish our results here on github and/or on some datascience blog.

We were wondering whether it would be ok to use this dataset (giving proper credit for it, of course)? Is the data released under any license?

Thanks,
V

**Comment by demirbilek95** [comment]
Hi,
You can use the data without problem. We would be more than happy to see your results, can you please share with us?
Thanks,
Doğan

**Comment by vgherard** [comment]
Thanks Doğan, we'll be more than happy to share our findings :-)

Bye,
Valerio
